osis:
  ceph:
    name: ceph
    region: default
    storage-classes: default
    version: 15.2.3
    rgw:
      endpoint: http://ceph.osis.ose.vmware.com:31383/admin
      access-key: <osis-accesskey>
      secret-key: <osis-secretkey>
    s3:
      endpoint: http://ceph.osis.ose.vmware.com:31383
      access-key: <osis-accesskey>
      secret-key: <osis-secretkey>
    console:
      endpoint: https://dashboard.ceph.osis.ose.vmware.com:30610
  api:
    version: 1.0.0

server:
  port: 8443
  verbose: true
  ssl:
    key-store: classpath:osis.p12
    key-store-password: <key store password>
    key-store-type: PKCS12
    key-alias: <key alias>

security:
  require-ssl: true
  jwt:
    enabled: false
    access-token-expiration-time: 15
    refresh_token_expiration_time: 262800
    token-issuer: http://ceph.osis.ose.vmware.com
    token-signing-key: thisisosis