# coding: utf-8

# flake8: noqa

"""
    Object Storage Interoperability Services API

    This is VMware Cloud Director Object Storage Interoperability Services API. Once storage platform vendor implements REST APIs complying with this specification, Object Storage Extension can integrate with the platform without coding effort.  # noqa: E501

    The version of the OpenAPI document: 1.0.0-oas3
    Contact: wachen@vmware.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.anonymoususer_api import AnonymoususerApi
from openapi_client.api.bucketlist_api import BucketlistApi
from openapi_client.api.bucketloggingid_api import BucketloggingidApi
from openapi_client.api.console_api import ConsoleApi
from openapi_client.api.info_api import InfoApi
from openapi_client.api.optional_api import OptionalApi
from openapi_client.api.required_api import RequiredApi
from openapi_client.api.s3capability_api import S3capabilityApi
from openapi_client.api.s3credential_api import S3credentialApi
from openapi_client.api.tenant_api import TenantApi
from openapi_client.api.token_api import TokenApi
from openapi_client.api.usage_api import UsageApi
from openapi_client.api.user_api import UserApi

# import ApiClient
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException
# import models into sdk package
from openapi_client.models.information import Information
from openapi_client.models.inline_response200 import InlineResponse200
from openapi_client.models.osis_bucket_meta import OsisBucketMeta
from openapi_client.models.osis_error import OsisError
from openapi_client.models.osis_s3_capabilities import OsisS3Capabilities
from openapi_client.models.osis_s3_capabilities_exclusions import OsisS3CapabilitiesExclusions
from openapi_client.models.osis_s3_credential import OsisS3Credential
from openapi_client.models.osis_tenant import OsisTenant
from openapi_client.models.osis_usage import OsisUsage
from openapi_client.models.osis_user import OsisUser
from openapi_client.models.page_info import PageInfo
from openapi_client.models.page_of_bucket_meta import PageOfBucketMeta
from openapi_client.models.page_of_s3_credentials import PageOfS3Credentials
from openapi_client.models.page_of_tenants import PageOfTenants
from openapi_client.models.page_of_users import PageOfUsers
from openapi_client.models.refresh_request import RefreshRequest
from openapi_client.models.refresh_response import RefreshResponse

